"""add_description_and_category_to_templates

Revision ID: 0bfd7cb9bc13
Revises: 33eb404eb2b3
Create Date: 2025-09-27 15:54:29.392637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bfd7cb9bc13'
down_revision: Union[str, Sequence[str], None] = '33eb404eb2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('templates', sa.Column('category', sa.String(length=100), nullable=True))
    
    # Update existing records with default category
    op.execute("UPDATE templates SET category = 'medical' WHERE category IS NULL")
    
    # Now make category NOT NULL
    op.alter_column('templates', 'category', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'category')
    op.drop_column('templates', 'description')
    # ### end Alembic commands ###
