"""Add DocumentUpload table for PDF tracking

Revision ID: 11e6a58a23a0
Revises: 0e2bb90c5203
Create Date: 2025-09-09 13:30:01.589700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11e6a58a23a0'
down_revision: Union[str, Sequence[str], None] = '0e2bb90c5203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_uploads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('s3_file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extraction_status', sa.String(length=20), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_document_uploads_created_at', 'document_uploads', ['created_at'], unique=False)
    op.create_index('idx_document_uploads_extraction_status', 'document_uploads', ['extraction_status'], unique=False)
    op.create_index('idx_document_uploads_user_id', 'document_uploads', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_document_uploads_user_id', table_name='document_uploads')
    op.drop_index('idx_document_uploads_extraction_status', table_name='document_uploads')
    op.drop_index('idx_document_uploads_created_at', table_name='document_uploads')
    op.drop_table('document_uploads')
    # ### end Alembic commands ###
