"""add_templates_table

Revision ID: 33eb404eb2b3
Revises: cc8848b2c396
Create Date: 2025-09-27 14:50:33.843676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33eb404eb2b3'
down_revision: Union[str, Sequence[str], None] = 'cc8848b2c396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('md_template', sa.Boolean(), nullable=False),
    sa.Column('s3_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_templates_created_at', 'templates', ['created_at'], unique=False)
    op.create_index('idx_templates_name', 'templates', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_templates_name', table_name='templates')
    op.drop_index('idx_templates_created_at', table_name='templates')
    op.drop_table('templates')
    # ### end Alembic commands ###
