"""Add new template fields

Revision ID: b31692dd6c74
Revises: e7a21913ea5a
Create Date: 2025-10-03 11:45:55.487846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b31692dd6c74'
down_revision: Union[str, Sequence[str], None] = 'e7a21913ea5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('templates_name_key'), 'templates', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('templates_name_key'), 'templates', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
