"""Added the Audit Log table

Revision ID: c3782ec9bde1
Revises: 7231deda8aa6
Create Date: 2025-08-21 10:12:09.263568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3782ec9bde1'
down_revision: Union[str, Sequence[str], None] = '7231deda8aa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('action_details', sa.String(length=500), nullable=True))
    op.drop_column('audit_logs', 'old_values')
    op.drop_column('audit_logs', 'table_name')
    op.drop_column('audit_logs', 'record_id')
    op.drop_column('audit_logs', 'new_values')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('new_values', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('record_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('table_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('old_values', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('audit_logs', 'action_details')
    # ### end Alembic commands ###
