"""add_generated_documents_table

Revision ID: cc8848b2c396
Revises: bbf2001ce0bd
Create Date: 2025-09-27 13:03:16.577203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc8848b2c396'
down_revision: Union[str, Sequence[str], None] = 'bbf2001ce0bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_group_id', sa.String(length=100), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('s3_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_generated_documents_created_at', 'generated_documents', ['created_at'], unique=False)
    op.create_index('idx_generated_documents_group_id', 'generated_documents', ['document_group_id'], unique=False)
    op.create_index('idx_generated_documents_type', 'generated_documents', ['document_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_generated_documents_type', table_name='generated_documents')
    op.drop_index('idx_generated_documents_group_id', table_name='generated_documents')
    op.drop_index('idx_generated_documents_created_at', table_name='generated_documents')
    op.drop_table('generated_documents')
    # ### end Alembic commands ###
