"""Removed the markdonw feature from the templates table

Revision ID: e7a21913ea5a
Revises: 0bfd7cb9bc13
Create Date: 2025-10-01 20:21:49.490993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7a21913ea5a'
down_revision: Union[str, Sequence[str], None] = '0bfd7cb9bc13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'md_template')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('md_template', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
